on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: slides/die-partei.md -o build/die-partei.html --html
        env:
          MARP_USER: root:root
      - uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: slides/die-piraten.md -o build/die-piraten.html --html
        env:
          MARP_USER: root:root

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "build"
      - id: deployment
        uses: actions/deploy-pages@v4
